parameters: {}
environment: {}
packages:
    - name: telegram
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: marco
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          websecure: false
          parameters: {}
          environment: 
            BOT_ID: "${BOT_ID}"
          annotations: {}
          limits: {}
